sudo: required
services:
  - docker

before_install:
  - docker build -t talhaahmedk/multi-service-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true talhaahmedk/multi-service-test npm run test -- --coverage

after_success:
  - docker build -t talhaahmedk/multi-client ./client
  - docker build -t talhaahmedk/multi-server ./server
  - docker build -t talhaahmedk/multi-nginx ./nginx
  - docker build -t talhaahmedk/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push talhaahmedk/multi-client
  - docker push talhaahmedk/multi-server
  - docker push talhaahmedk/multi-nginx 
  - docker push talhaahmedk/multi-worker